# Publish all joint states -----------------------------------
mouse_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  
  

# Effort Controllers ---------------------------------------
  
mouse_leftBWheel_effort_controller:
  type: effort_controllers/JointVelocityController
  joint: leg_wheel_LB_joint
  pid: {p: 1.0, i: 0.0, d: 0.0}
mouse_rightBWheel_effort_controller:
  type: effort_controllers/JointVelocityController
  joint: leg_wheel_RB_joint
  pid: {p: 1.0, i: 0.0, d: 0.0}
mouse_leftSpinner_effort_controller:
  type: effort_controllers/JointVelocityController
  joint: leg_LF_spinner_joint
  pid: {p: 1.0, i: 0.0, d: 0.0}
mouse_rightSpinner_effort_controller:
  type: effort_controllers/JointVelocityController
  joint: leg_RF_spinner_joint
  pid: {p: 1.0, i: 0.0, d: 0.0}
