cat:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Effort Controllers ---------------------------------------
  leftWheel_effort_controller:
    type: effort_controllers/JointVelocityController
    joint: leg_wheel_LF_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  rightWheel_effort_controller:
    type: effort_controllers/JointVelocityController
    joint: leg_wheel_RF_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
